package com.brianyi.domain;

public class Business {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.b_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String bName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.cname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.contacts_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String contactsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.product_type
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Byte productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.b_stage
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Byte bStage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.b_source
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Byte bSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.clientcid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer clientcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.sysusersys_user_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer sysusersysUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bid
     *
     * @return the value of business.bid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bid
     *
     * @param bid the value for business.bid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.b_name
     *
     * @return the value of business.b_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getbName() {
        return bName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.b_name
     *
     * @param bName the value for business.b_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setbName(String bName) {
        this.bName = bName == null ? null : bName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.cname
     *
     * @return the value of business.cname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.cname
     *
     * @param cname the value for business.cname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.contacts_name
     *
     * @return the value of business.contacts_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getContactsName() {
        return contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.contacts_name
     *
     * @param contactsName the value for business.contacts_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setContactsName(String contactsName) {
        this.contactsName = contactsName == null ? null : contactsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.product_type
     *
     * @return the value of business.product_type
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Byte getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.product_type
     *
     * @param productType the value for business.product_type
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setProductType(Byte productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.b_stage
     *
     * @return the value of business.b_stage
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Byte getbStage() {
        return bStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.b_stage
     *
     * @param bStage the value for business.b_stage
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setbStage(Byte bStage) {
        this.bStage = bStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.b_source
     *
     * @return the value of business.b_source
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Byte getbSource() {
        return bSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.b_source
     *
     * @param bSource the value for business.b_source
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setbSource(Byte bSource) {
        this.bSource = bSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.clientcid
     *
     * @return the value of business.clientcid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getClientcid() {
        return clientcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.clientcid
     *
     * @param clientcid the value for business.clientcid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setClientcid(Integer clientcid) {
        this.clientcid = clientcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.sysusersys_user_id
     *
     * @return the value of business.sysusersys_user_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getSysusersysUserId() {
        return sysusersysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.sysusersys_user_id
     *
     * @param sysusersysUserId the value for business.sysusersys_user_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setSysusersysUserId(Integer sysusersysUserId) {
        this.sysusersysUserId = sysusersysUserId;
    }
}