package com.brianyi.domain;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.contacts_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String contactsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.phone
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.position
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.industry
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.wechat_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String wechatName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.email
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.c_notes
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String cNotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.c_source
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Byte cSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.tel
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.website
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.province
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.city
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.area
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.address
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cid
     *
     * @return the value of client.cid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cid
     *
     * @param cid the value for client.cid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cname
     *
     * @return the value of client.cname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cname
     *
     * @param cname the value for client.cname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.contacts_name
     *
     * @return the value of client.contacts_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getContactsName() {
        return contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.contacts_name
     *
     * @param contactsName the value for client.contacts_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setContactsName(String contactsName) {
        this.contactsName = contactsName == null ? null : contactsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.phone
     *
     * @return the value of client.phone
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.phone
     *
     * @param phone the value for client.phone
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.position
     *
     * @return the value of client.position
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.position
     *
     * @param position the value for client.position
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.industry
     *
     * @return the value of client.industry
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.industry
     *
     * @param industry the value for client.industry
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.wechat_name
     *
     * @return the value of client.wechat_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getWechatName() {
        return wechatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.wechat_name
     *
     * @param wechatName the value for client.wechat_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setWechatName(String wechatName) {
        this.wechatName = wechatName == null ? null : wechatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.email
     *
     * @return the value of client.email
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.email
     *
     * @param email the value for client.email
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.c_notes
     *
     * @return the value of client.c_notes
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getcNotes() {
        return cNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.c_notes
     *
     * @param cNotes the value for client.c_notes
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setcNotes(String cNotes) {
        this.cNotes = cNotes == null ? null : cNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.c_source
     *
     * @return the value of client.c_source
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Byte getcSource() {
        return cSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.c_source
     *
     * @param cSource the value for client.c_source
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setcSource(Byte cSource) {
        this.cSource = cSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.tel
     *
     * @return the value of client.tel
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.tel
     *
     * @param tel the value for client.tel
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.website
     *
     * @return the value of client.website
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.website
     *
     * @param website the value for client.website
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.province
     *
     * @return the value of client.province
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.province
     *
     * @param province the value for client.province
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.city
     *
     * @return the value of client.city
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.city
     *
     * @param city the value for client.city
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.area
     *
     * @return the value of client.area
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.area
     *
     * @param area the value for client.area
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.address
     *
     * @return the value of client.address
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.address
     *
     * @param address the value for client.address
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}