package com.brianyi.domain;

import java.util.Date;

public class Contract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.cname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.signer
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String signer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_date
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Date contractDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.invoicing_flag
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Byte invoicingFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.order_clerck
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String orderClerck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.notes
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_attachment_url
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer contractAttachmentUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.clientcid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer clientcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.sysusersys_user_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer sysusersysUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_id
     *
     * @return the value of contract.contract_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_id
     *
     * @param contractId the value for contract.contract_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.cname
     *
     * @return the value of contract.cname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.cname
     *
     * @param cname the value for contract.cname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.signer
     *
     * @return the value of contract.signer
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getSigner() {
        return signer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.signer
     *
     * @param signer the value for contract.signer
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setSigner(String signer) {
        this.signer = signer == null ? null : signer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_date
     *
     * @return the value of contract.contract_date
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Date getContractDate() {
        return contractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_date
     *
     * @param contractDate the value for contract.contract_date
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.invoicing_flag
     *
     * @return the value of contract.invoicing_flag
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Byte getInvoicingFlag() {
        return invoicingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.invoicing_flag
     *
     * @param invoicingFlag the value for contract.invoicing_flag
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setInvoicingFlag(Byte invoicingFlag) {
        this.invoicingFlag = invoicingFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.order_clerck
     *
     * @return the value of contract.order_clerck
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getOrderClerck() {
        return orderClerck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.order_clerck
     *
     * @param orderClerck the value for contract.order_clerck
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setOrderClerck(String orderClerck) {
        this.orderClerck = orderClerck == null ? null : orderClerck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.notes
     *
     * @return the value of contract.notes
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.notes
     *
     * @param notes the value for contract.notes
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_attachment_url
     *
     * @return the value of contract.contract_attachment_url
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getContractAttachmentUrl() {
        return contractAttachmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_attachment_url
     *
     * @param contractAttachmentUrl the value for contract.contract_attachment_url
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setContractAttachmentUrl(Integer contractAttachmentUrl) {
        this.contractAttachmentUrl = contractAttachmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.clientcid
     *
     * @return the value of contract.clientcid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getClientcid() {
        return clientcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.clientcid
     *
     * @param clientcid the value for contract.clientcid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setClientcid(Integer clientcid) {
        this.clientcid = clientcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.sysusersys_user_id
     *
     * @return the value of contract.sysusersys_user_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getSysusersysUserId() {
        return sysusersysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.sysusersys_user_id
     *
     * @param sysusersysUserId the value for contract.sysusersys_user_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setSysusersysUserId(Integer sysusersysUserId) {
        this.sysusersysUserId = sysusersysUserId;
    }
}