package com.brianyi.domain;

public class DepartmentOne {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.did
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.d_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.d_rank
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Boolean dRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.d_parent_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer dParentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.did
     *
     * @return the value of department.did
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.did
     *
     * @param did the value for department.did
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.d_name
     *
     * @return the value of department.d_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.d_name
     *
     * @param dName the value for department.d_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.d_rank
     *
     * @return the value of department.d_rank
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Boolean getdRank() {
        return dRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.d_rank
     *
     * @param dRank the value for department.d_rank
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setdRank(Boolean dRank) {
        this.dRank = dRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.d_parent_id
     *
     * @return the value of department.d_parent_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getdParentId() {
        return dParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.d_parent_id
     *
     * @param dParentId the value for department.d_parent_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setdParentId(Integer dParentId) {
        this.dParentId = dParentId;
    }
}