package com.brianyi.domain;

public class Enterprise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.clientcid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer clientcid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_id
     *
     * @return the value of enterprise.enterprise_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_id
     *
     * @param enterpriseId the value for enterprise.enterprise_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_name
     *
     * @return the value of enterprise.enterprise_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_name
     *
     * @param enterpriseName the value for enterprise.enterprise_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.clientcid
     *
     * @return the value of enterprise.clientcid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getClientcid() {
        return clientcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.clientcid
     *
     * @param clientcid the value for enterprise.clientcid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setClientcid(Integer clientcid) {
        this.clientcid = clientcid;
    }
}