package com.brianyi.domain;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_type
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Byte mType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_content
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String mContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_time
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Date mTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_delete_flag
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Byte mDeleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sysusersys_user_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer sysusersysUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mid
     *
     * @return the value of message.mid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mid
     *
     * @param mid the value for message.mid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_type
     *
     * @return the value of message.m_type
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Byte getmType() {
        return mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_type
     *
     * @param mType the value for message.m_type
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setmType(Byte mType) {
        this.mType = mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_content
     *
     * @return the value of message.m_content
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getmContent() {
        return mContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_content
     *
     * @param mContent the value for message.m_content
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setmContent(String mContent) {
        this.mContent = mContent == null ? null : mContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_time
     *
     * @return the value of message.m_time
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Date getmTime() {
        return mTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_time
     *
     * @param mTime the value for message.m_time
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setmTime(Date mTime) {
        this.mTime = mTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_delete_flag
     *
     * @return the value of message.m_delete_flag
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Byte getmDeleteFlag() {
        return mDeleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_delete_flag
     *
     * @param mDeleteFlag the value for message.m_delete_flag
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setmDeleteFlag(Byte mDeleteFlag) {
        this.mDeleteFlag = mDeleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sysusersys_user_id
     *
     * @return the value of message.sysusersys_user_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getSysusersysUserId() {
        return sysusersysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sysusersys_user_id
     *
     * @param sysusersysUserId the value for message.sysusersys_user_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setSysusersysUserId(Integer sysusersysUserId) {
        this.sysusersysUserId = sysusersysUserId;
    }
}