package com.brianyi.domain;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.p_create_time
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer pCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.p_create_person
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer pCreatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.p_create_time
     *
     * @return the value of product.p_create_time
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getpCreateTime() {
        return pCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.p_create_time
     *
     * @param pCreateTime the value for product.p_create_time
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setpCreateTime(Integer pCreateTime) {
        this.pCreateTime = pCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.p_create_person
     *
     * @return the value of product.p_create_person
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getpCreatePerson() {
        return pCreatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.p_create_person
     *
     * @param pCreatePerson the value for product.p_create_person
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setpCreatePerson(Integer pCreatePerson) {
        this.pCreatePerson = pCreatePerson;
    }
}