package com.brianyi.domain;

public class SysBackendApi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backend_api.backend_api_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String backendApiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backend_api.backend_api_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String backendApiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backend_api.backend_api_method
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String backendApiMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backend_api.backend_api_url
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String backendApiUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backend_api.pid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backend_api.backend_api_sort
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer backendApiSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_backend_api.description
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backend_api.backend_api_id
     *
     * @return the value of sys_backend_api.backend_api_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getBackendApiId() {
        return backendApiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backend_api.backend_api_id
     *
     * @param backendApiId the value for sys_backend_api.backend_api_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setBackendApiId(String backendApiId) {
        this.backendApiId = backendApiId == null ? null : backendApiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backend_api.backend_api_name
     *
     * @return the value of sys_backend_api.backend_api_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getBackendApiName() {
        return backendApiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backend_api.backend_api_name
     *
     * @param backendApiName the value for sys_backend_api.backend_api_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setBackendApiName(String backendApiName) {
        this.backendApiName = backendApiName == null ? null : backendApiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backend_api.backend_api_method
     *
     * @return the value of sys_backend_api.backend_api_method
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getBackendApiMethod() {
        return backendApiMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backend_api.backend_api_method
     *
     * @param backendApiMethod the value for sys_backend_api.backend_api_method
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setBackendApiMethod(String backendApiMethod) {
        this.backendApiMethod = backendApiMethod == null ? null : backendApiMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backend_api.backend_api_url
     *
     * @return the value of sys_backend_api.backend_api_url
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getBackendApiUrl() {
        return backendApiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backend_api.backend_api_url
     *
     * @param backendApiUrl the value for sys_backend_api.backend_api_url
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setBackendApiUrl(String backendApiUrl) {
        this.backendApiUrl = backendApiUrl == null ? null : backendApiUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backend_api.pid
     *
     * @return the value of sys_backend_api.pid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backend_api.pid
     *
     * @param pid the value for sys_backend_api.pid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backend_api.backend_api_sort
     *
     * @return the value of sys_backend_api.backend_api_sort
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getBackendApiSort() {
        return backendApiSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backend_api.backend_api_sort
     *
     * @param backendApiSort the value for sys_backend_api.backend_api_sort
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setBackendApiSort(Integer backendApiSort) {
        this.backendApiSort = backendApiSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_backend_api.description
     *
     * @return the value of sys_backend_api.description
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_backend_api.description
     *
     * @param description the value for sys_backend_api.description
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}