package com.brianyi.domain;

public class SysFrontendMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frontend_menu.fronted_menu_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String frontedMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frontend_menu.frontend_menu_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String frontendMenuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frontend_menu.frontend_menu_url
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String frontendMenuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frontend_menu.pid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frontend_menu.fronted_menu_sort
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private Integer frontedMenuSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frontend_menu.description
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frontend_menu.fronted_menu_id
     *
     * @return the value of sys_frontend_menu.fronted_menu_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getFrontedMenuId() {
        return frontedMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frontend_menu.fronted_menu_id
     *
     * @param frontedMenuId the value for sys_frontend_menu.fronted_menu_id
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setFrontedMenuId(String frontedMenuId) {
        this.frontedMenuId = frontedMenuId == null ? null : frontedMenuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frontend_menu.frontend_menu_name
     *
     * @return the value of sys_frontend_menu.frontend_menu_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getFrontendMenuName() {
        return frontendMenuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frontend_menu.frontend_menu_name
     *
     * @param frontendMenuName the value for sys_frontend_menu.frontend_menu_name
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setFrontendMenuName(String frontendMenuName) {
        this.frontendMenuName = frontendMenuName == null ? null : frontendMenuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frontend_menu.frontend_menu_url
     *
     * @return the value of sys_frontend_menu.frontend_menu_url
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getFrontendMenuUrl() {
        return frontendMenuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frontend_menu.frontend_menu_url
     *
     * @param frontendMenuUrl the value for sys_frontend_menu.frontend_menu_url
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setFrontendMenuUrl(String frontendMenuUrl) {
        this.frontendMenuUrl = frontendMenuUrl == null ? null : frontendMenuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frontend_menu.pid
     *
     * @return the value of sys_frontend_menu.pid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frontend_menu.pid
     *
     * @param pid the value for sys_frontend_menu.pid
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frontend_menu.fronted_menu_sort
     *
     * @return the value of sys_frontend_menu.fronted_menu_sort
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public Integer getFrontedMenuSort() {
        return frontedMenuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frontend_menu.fronted_menu_sort
     *
     * @param frontedMenuSort the value for sys_frontend_menu.fronted_menu_sort
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setFrontedMenuSort(Integer frontedMenuSort) {
        this.frontedMenuSort = frontedMenuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frontend_menu.description
     *
     * @return the value of sys_frontend_menu.description
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frontend_menu.description
     *
     * @param description the value for sys_frontend_menu.description
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}