package com.brianyi.mapper;

import com.brianyi.domain.Business;
import com.brianyi.domain.BusinessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    long countByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int deleteByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int insert(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int insertSelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    List<Business> selectByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") Business record, @Param("example") BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int updateByExample(@Param("record") Business record, @Param("example") BusinessExample example);
}