package com.brianyi.mapper;

import com.brianyi.domain.DepartmentOne;
import com.brianyi.domain.DepartmentOneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentOneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    long countByExample(DepartmentOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int deleteByExample(DepartmentOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int insert(DepartmentOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int insertSelective(DepartmentOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    List<DepartmentOne> selectByExample(DepartmentOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") DepartmentOne record, @Param("example") DepartmentOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int updateByExample(@Param("record") DepartmentOne record, @Param("example") DepartmentOneExample example);
}