package com.brianyi.mapper;

import com.brianyi.domain.SysBackendApi;
import com.brianyi.domain.SysBackendApiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysBackendApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_backend_api
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    long countByExample(SysBackendApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_backend_api
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int deleteByExample(SysBackendApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_backend_api
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int insert(SysBackendApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_backend_api
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int insertSelective(SysBackendApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_backend_api
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    List<SysBackendApi> selectByExample(SysBackendApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_backend_api
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysBackendApi record, @Param("example") SysBackendApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_backend_api
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int updateByExample(@Param("record") SysBackendApi record, @Param("example") SysBackendApiExample example);
}