package com.brianyi.mapper;

import com.brianyi.domain.SysFrontendMenu;
import com.brianyi.domain.SysFrontendMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysFrontendMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frontend_menu
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    long countByExample(SysFrontendMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frontend_menu
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int deleteByExample(SysFrontendMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frontend_menu
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int insert(SysFrontendMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frontend_menu
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int insertSelective(SysFrontendMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frontend_menu
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    List<SysFrontendMenu> selectByExample(SysFrontendMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frontend_menu
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysFrontendMenu record, @Param("example") SysFrontendMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frontend_menu
     *
     * @mbg.generated Tue Nov 24 14:16:07 CST 2020
     */
    int updateByExample(@Param("record") SysFrontendMenu record, @Param("example") SysFrontendMenuExample example);
}